### ISSUE TITLE
[question]why arc-marko is removed in v2

### ISSUE THREAD

**Issue by huang-L** [eBay/arc#4]
Hi, eBay/arc team

I am a developer from ebay...

I am curious why arc-marko is removed in v2?
What If I want to integrate marko with arc, how can I do?

ps: our ui project is taking advantage of marko and lasso.  at mean time, it needs to be adaptive to different devices, like desktop and mobile

**Comment by mlrawlings** [comment]
Good question.  `arc@1` required a proxy to be configured based on what was being adapted.  `arc-marko` was one of these proxies.

Version 2 of `arc` is taking a more generic approach, which means that package is no longer necessary.  I have an example Marko app that I can add to the repo.  I'll leave this issue open until it's added.

There are still some limitations around the current approach:

- a tag will need to have a "base tag" (one without flags)
- flagged versions of a tag will need to be siblings in the file tree

So using Marko with `arc@2` currently looks like this
```
components/
    custom-tag/
        index.marko
    custom-tag[mobile]/
        index.marko
```

This is part of the reason why why v2 is still in alpha, but I believe we have a viable solution for these current limitations.  You should eventually be able to have a structure that looks more like using Marko with `arc@1` (but no need for the `index.arc` file):

```
components/
    custom-tag/
        [desktop]/
            index.marko
        [mobile]/
            index.marko
```

**Comment by huang-L** [comment]
thanks for the reply. very appreciate it

**Comment by mlrawlings** [comment]
The (wip) Marko example is here:
https://github.com/eBay/arc/tree/master/packages/example-marko-lasso
